"""spartun — SPaRTUN spatial-reasoning experiments."""
from config import (
    DEFAULT_GPT_MODEL,
    DEFAULT_GPT_MINI_MODEL,
    SPARTUN_OLLAMA_MODEL as DEFAULT_OLLAMA_MODEL,
    TEXT_ONLY_OLLAMA_MODEL,
)

__all__ = ["DEFAULT_GPT_MODEL", "DEFAULT_GPT_MINI_MODEL", "DEFAULT_OLLAMA_MODEL", "TEXT_ONLY_OLLAMA_MODEL"]

